-- S1: platform defaults that are the same for every state.

INSERT INTO cfg.option_set (code, description) VALUES
  ('PARTY_TYPE','Party type on the common party block'),
  ('TRANSFER_SCOPE','Physical nature of the transfer'),
  ('SALE_SUBTYPE','Sale sub-type'),
  ('MODE_OF_CONSIDERATION','How consideration was paid'),
  ('PAYMENT_MODE','How registration fees were paid'),
  ('PROPERTY_TYPE','Kind of property record'),
  ('LAND_TYPE','Revenue land context'),
  ('CLASSIFICATION','Land classification'),
  ('EXTENT_UNIT','Extent units'),
  ('BASIS_OF_SETTLEMENT','Why a settlement is being made'),
  ('ID_PROOF_TYPE','Witness identity proof'),
  ('MARKER_STATUS','Boundary marker condition'),
  ('MUTATION_TYPE','Revenue mutation type'),
  ('NATURE_OF_TITLE','How the current owner acquired title');

INSERT INTO cfg.option_value (option_set_code, value_code, label, sort_order) VALUES
  ('PARTY_TYPE','INDIVIDUAL','Individual',1),
  ('PARTY_TYPE','HUF','Hindu Undivided Family',2),
  ('PARTY_TYPE','INSTITUTION','Institution',3),
  ('PARTY_TYPE','AUTHORISED_REPRESENTATIVE','Authorised Representative',4),
  ('TRANSFER_SCOPE','FULL_PROPERTY','Full Property',1),
  ('TRANSFER_SCOPE','UNDIVIDED_SHARE','Undivided Share',2),
  ('TRANSFER_SCOPE','PHYSICAL_PARTIAL_EXTENT_SUBDIVISION','Physical Partial Extent / Subdivision',3),
  ('SALE_SUBTYPE','FULL_PROPERTY','Full Property',1),
  ('SALE_SUBTYPE','UNDIVIDED_SHARE','Undivided Share',2),
  ('SALE_SUBTYPE','PARTIAL_SUBDIVISION','Partial Property / Subdivision',3),
  ('MODE_OF_CONSIDERATION','BANK_TRANSFER','Bank Transfer (NEFT/RTGS)',1),
  ('MODE_OF_CONSIDERATION','DEMAND_DRAFT','Demand Draft',2),
  ('MODE_OF_CONSIDERATION','CHEQUE','Cheque',3),
  ('MODE_OF_CONSIDERATION','CASH','Cash',4),
  ('PAYMENT_MODE','E_CHALLAN','e-Challan',1),
  ('PAYMENT_MODE','UPI','UPI',2),
  ('PAYMENT_MODE','CARD','Card',3),
  ('PAYMENT_MODE','DD','Demand Draft',4),
  ('PROPERTY_TYPE','LAND','Land Parcel',1),
  ('PROPERTY_TYPE','HOUSE_SITE','House Site',2),
  ('PROPERTY_TYPE','BUILDING','Building',3),
  ('PROPERTY_TYPE','APARTMENT_UNIT','Apartment / Flat',4),
  ('PROPERTY_TYPE','AGRICULTURAL','Agricultural Land',5),
  ('LAND_TYPE','RURAL','Rural',1),
  ('LAND_TYPE','NATHAM','Natham (House Site)',2),
  ('CLASSIFICATION','WET','Wet (Nanjai)',1),
  ('CLASSIFICATION','DRY','Dry (Punjai)',2),
  ('CLASSIFICATION','MANAVARI','Manavari',3),
  ('CLASSIFICATION','HOUSE_SITE','House Site',4),
  ('EXTENT_UNIT','SQ_FT','Square Feet',1),
  ('EXTENT_UNIT','SQ_M','Square Metres',2),
  ('EXTENT_UNIT','CENT','Cent',3),
  ('EXTENT_UNIT','ACRE','Acre',4),
  ('EXTENT_UNIT','HECTARE','Hectare',5),
  ('BASIS_OF_SETTLEMENT','FAMILY_ARRANGEMENT','Family Arrangement',1),
  ('BASIS_OF_SETTLEMENT','ANTICIPATED_SUCCESSION','Anticipated Succession',2),
  ('BASIS_OF_SETTLEMENT','DISPUTE_RESOLUTION','Dispute Resolution',3),
  ('BASIS_OF_SETTLEMENT','OTHER','Other',4),
  ('ID_PROOF_TYPE','AADHAAR','Aadhaar',1),
  ('ID_PROOF_TYPE','VOTER_ID','Voter ID',2),
  ('ID_PROOF_TYPE','DRIVING_LICENCE','Driving Licence',3),
  ('ID_PROOF_TYPE','PASSPORT','Passport',4),
  ('MARKER_STATUS','PRESENT','Present',1),
  ('MARKER_STATUS','MISSING','Missing',2),
  ('MARKER_STATUS','DISPUTED','Disputed',3),
  ('MUTATION_TYPE','FULL_PROPERTY_TRANSFER','Full Property Transfer',1),
  ('MUTATION_TYPE','JOINT_OWNERSHIP','Joint Ownership',2),
  ('MUTATION_TYPE','UNDIVIDED_SHARE','Undivided Share',3),
  ('MUTATION_TYPE','SUBDIVISION','Subdivision',4),
  ('MUTATION_TYPE','GIFT_SETTLEMENT_TRANSFER','Gift / Settlement Transfer',5),
  ('MUTATION_TYPE','RELEASE_RELINQUISHMENT','Release / Relinquishment',6),
  ('MUTATION_TYPE','OTHER','Other',7),
  ('NATURE_OF_TITLE','PURCHASE','Purchase',1),
  ('NATURE_OF_TITLE','INHERITANCE','Inheritance',2),
  ('NATURE_OF_TITLE','GIFT','Gift',3),
  ('NATURE_OF_TITLE','SETTLEMENT','Settlement',4),
  ('NATURE_OF_TITLE','PARTITION','Partition',5),
  ('NATURE_OF_TITLE','GOVERNMENT_GRANT','Government Grant',6);

INSERT INTO master.document_type (code, name, applies_to, allowed_mime, max_size_mb) VALUES
  ('DEED','Registered Deed','{TRANSACTION}','{application/pdf}',20),
  ('TITLE_DOC','Prior Title Document','{PROPERTY,TRANSACTION}','{application/pdf,image/jpeg,image/png}',20),
  ('EC_COPY','Encumbrance Certificate Copy','{PROPERTY,TRANSACTION}','{application/pdf}',10),
  ('PATTA_CHITTA','Patta / Chitta Extract','{PROPERTY}','{application/pdf,image/jpeg}',10),
  ('FMB_SKETCH','FMB / Survey Sketch','{SURVEY}','{application/pdf,image/jpeg,image/png}',20),
  ('SITE_PHOTO','Site Photograph','{SURVEY}','{image/jpeg,image/png}',10),
  ('FAMILY_ARRANGEMENT','Family Arrangement Memorandum','{TRANSACTION}','{application/pdf}',10),
  ('OBJECTION_DOC','Objection Supporting Document','{REVENUE}','{application/pdf,image/jpeg}',10),
  ('ID_PROOF','Identity Proof','{TRANSACTION}','{application/pdf,image/jpeg,image/png}',5);

INSERT INTO master.relationship (code, name, fee_category, sort_order) VALUES
  ('SPOUSE','Spouse','FAMILY',1),
  ('SON','Son','FAMILY',2),
  ('DAUGHTER','Daughter','FAMILY',3),
  ('FATHER','Father','FAMILY',4),
  ('MOTHER','Mother','FAMILY',5),
  ('BROTHER','Brother','FAMILY',6),
  ('SISTER','Sister','FAMILY',7),
  ('GRANDCHILD','Grandchild','FAMILY',8),
  ('OTHER_RELATIVE','Other Relative','NON_FAMILY',9),
  ('UNRELATED','Unrelated','NON_FAMILY',10);

INSERT INTO sec.permission (code, description) VALUES
  ('PROPERTY_CREATE','Create a property record'),
  ('PROPERTY_READ','Read property records in jurisdiction'),
  ('TXN_CREATE','Initiate a transaction'),
  ('TXN_EDIT','Edit an unregistered transaction'),
  ('TXN_READ','Read transactions in jurisdiction'),
  ('CONSENT_CAPTURE','Request and verify Aadhaar OTP consent'),
  ('RULE_CHECK_RUN','Run the rule check engines'),
  ('RULE_CHECK_READ','View rule check findings'),
  ('FEE_CALCULATE','Calculate fees'),
  ('PAYMENT_RECORD','Record a payment'),
  ('REGISTER','Complete registration'),
  ('SURVEY_SCHEDULE','Propose or accept a site visit'),
  ('SURVEY_SUBMIT','Submit survey and FMB data'),
  ('REVENUE_VERIFY','Verify and forward a proposed mutation'),
  ('REVENUE_OBJECTION','Record a revenue objection'),
  ('REVENUE_APPROVE','Issue the final mutation decision'),
  ('TOKEN_READ','View token and chain state'),
  ('VERIFY_RUN','Run an on-chain verification'),
  ('ADMIN_CONFIG','Manage configuration and masters'),
  ('AUDIT_READ','Read the audit trail'),
  ('INGEST_RECORD_MODE','Ingest outcomes in RECORD mode');

INSERT INTO sec.role (code, name, department, description) VALUES
  ('REGISTRATION_OFFICER','Registration Officer','REGISTRATION','Initiates and registers every transaction'),
  ('SURVEYOR','Surveyor','SURVEY','Performs boundary survey and submits FMB data'),
  ('VAO','Village Administrative Officer','REVENUE','Verifies and forwards revenue mutations'),
  ('TAHSILDAR','Tahsildar','REVENUE','Sole issuer of the final mutation decision'),
  ('STATE_ADMIN','State Administrator','ADMIN','Manages configuration, masters and users'),
  ('PUBLIC_VIEWER','Public Viewer','PUBLIC','Reads only the common public property view');

INSERT INTO sec.role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sec.role r, sec.permission p
WHERE (r.code = 'REGISTRATION_OFFICER' AND p.code IN
        ('PROPERTY_CREATE','PROPERTY_READ','TXN_CREATE','TXN_EDIT','TXN_READ','CONSENT_CAPTURE',
         'RULE_CHECK_RUN','RULE_CHECK_READ','FEE_CALCULATE','PAYMENT_RECORD','REGISTER',
         'TOKEN_READ','VERIFY_RUN','AUDIT_READ'))
   OR (r.code = 'SURVEYOR' AND p.code IN
        ('PROPERTY_READ','TXN_READ','SURVEY_SCHEDULE','SURVEY_SUBMIT','TOKEN_READ','AUDIT_READ'))
   OR (r.code = 'VAO' AND p.code IN
        ('PROPERTY_READ','TXN_READ','SURVEY_SCHEDULE','REVENUE_VERIFY','REVENUE_OBJECTION',
         'RULE_CHECK_READ','TOKEN_READ','AUDIT_READ'))
   OR (r.code = 'TAHSILDAR' AND p.code IN
        ('PROPERTY_READ','TXN_READ','REVENUE_VERIFY','REVENUE_APPROVE','RULE_CHECK_READ',
         'TOKEN_READ','AUDIT_READ'))
   OR (r.code = 'STATE_ADMIN' AND p.code IN
        ('PROPERTY_READ','TXN_READ','ADMIN_CONFIG','AUDIT_READ','TOKEN_READ','VERIFY_RUN',
         'RULE_CHECK_READ','INGEST_RECORD_MODE'))
   OR (r.code = 'PUBLIC_VIEWER' AND p.code IN ('TOKEN_READ'));

INSERT INTO cfg.feature_flag (flag_code, enabled, description) VALUES
  ('RULES_BLOCKING', FALSE, 'Pilot: rule check findings are advisory and never block a transition'),
  ('PUBLIC_VIEW_ENABLED', TRUE, 'Expose the common public property view'),
  ('CHAIN_ANCHOR_PER_TRANSACTION', TRUE, 'Anchor an evidence Merkle root per transaction'),
  ('SURVEY_GPS_MANDATORY', FALSE, 'Require a GPS centroid reading on every survey submission');

INSERT INTO master.system_config (key, value_json, description) VALUES
  ('consent.text.version', '"CONSENT-V1"', 'Version of the consent text presented to parties'),
  ('ec.default.lookback.years', '30', 'Default EC search window when none is configured per state'),
  ('survey.default.tolerance.pct', '1.0', 'Default extent variance tolerance for survey submissions');

-- Field definitions drive the config-driven forms in the UI.
INSERT INTO cfg.field_definition (entity, field_code, data_type, pii, public_view_safe) VALUES
  ('PROPERTY','ulpin','TEXT',false,true),
  ('PROPERTY','propertyTypeCode','ENUM',false,true),
  ('PROPERTY','landTypeCode','ENUM',false,true),
  ('PROPERTY','classificationCode','ENUM',false,true),
  ('PROPERTY','extentValue','DECIMAL',false,true),
  ('PROPERTY','extentUnit','ENUM',false,true),
  ('PROPERTY','surveyNo','TEXT',false,true),
  ('PROPERTY','subdivisionNo','TEXT',false,true),
  ('PROPERTY','districtCode','TEXT',false,true),
  ('PROPERTY','talukCode','TEXT',false,true),
  ('PROPERTY','villageCode','TEXT',false,true),
  ('PROPERTY','sroCode','TEXT',false,false),
  ('PROPERTY','doorNo','TEXT',false,false),
  ('PROPERTY','street','TEXT',false,false),
  ('PROPERTY','boundaryNorth','TEXT',false,false),
  ('PROPERTY','boundarySouth','TEXT',false,false),
  ('PROPERTY','boundaryEast','TEXT',false,false),
  ('PROPERTY','boundaryWest','TEXT',false,false),
  ('TRANSACTION','deedTypeCode','ENUM',false,false),
  ('TRANSACTION','subtype','ENUM',false,false),
  ('TRANSACTION','transferScope','ENUM',false,false),
  ('TRANSACTION','declaredConsideration','MONEY',false,false),
  ('TRANSACTION','modeOfConsideration','ENUM',false,false),
  ('TRANSACTION','extentOrShareTransferred','DECIMAL',false,false),
  ('TRANSACTION','guidelineValue','MONEY',false,false),
  ('TRANSACTION','relationshipCategory','ENUM',false,false),
  ('TRANSACTION','basisOfSettlement','ENUM',false,false),
  ('TRANSACTION','shareBeingReleased','DECIMAL',false,false),
  ('TRANSACTION','resultingSubparcelCount','INT',false,false),
  ('TRANSACTION','sroCode','TEXT',false,false),
  ('PARTY','partyType','ENUM',false,false),
  ('PARTY','name','TEXT',true,false),
  ('PARTY','aadhaarNumber','TEXT',true,false),
  ('PARTY','kartaName','TEXT',true,false),
  ('PARTY','kartaAadhaarNumber','TEXT',true,false),
  ('PARTY','pan','TEXT',true,false),
  ('PARTY','address','TEXT',true,false),
  ('PARTY','relationshipCode','ENUM',false,false),
  ('PARTY','existingSharePct','DECIMAL',false,false),
  ('PARTY','shareTransferredPct','DECIMAL',false,false),
  ('PARTY','extentTransferred','DECIMAL',false,false),
  ('PARTY','resultingSharePct','DECIMAL',false,false),
  ('PARTY','authorityPoaReference','TEXT',false,false);

-- Cross-field validation rules, evaluated by the backend validation engine and
-- mirrored in the UI. ERROR blocks the transition; WARN is advisory.
INSERT INTO cfg.validation_rule (deed_type_code, scope, rule_code, expression, severity, message) VALUES
  ('*','TRANSACTION','SIDES_RECONCILE','sideTotalsReconcile','ERROR',
   'Total share/extent given up by Side 1 must equal the total received by Side 2'),
  ('*','TRANSACTION','MIN_ONE_PARTY_PER_SIDE','minOnePartyPerSide','ERROR',
   'Each side of the transaction must have at least one party'),
  ('*','TRANSACTION','WITNESS_MINIMUM','witnessMinimumMet','ERROR',
   'The minimum witness count for this deed type has not been met'),
  ('*','TRANSACTION','CONSENT_ALL_VERIFIED','allPartiesConsentVerified','ERROR',
   'Every party on both sides must show Verified Aadhaar OTP consent before registration'),
  ('*','TRANSACTION','GUIDELINE_VALUE_PRESENT','guidelineValuePresent','ERROR',
   'Guideline value must be entered before fees can be calculated'),
  ('*','TRANSACTION','FEES_PAID','feesFullyPaid','ERROR',
   'Recorded payments must cover the calculated total payable'),
  ('SALE_FULL','TRANSACTION','CONSIDERATION_REQUIRED','considerationPositive','ERROR',
   'A sale must declare a positive consideration'),
  ('SALE_UNDIVIDED_SHARE','TRANSACTION','CONSIDERATION_REQUIRED','considerationPositive','ERROR',
   'A sale must declare a positive consideration'),
  ('SALE_PARTIAL_SUBDIVISION','TRANSACTION','CONSIDERATION_REQUIRED','considerationPositive','ERROR',
   'A sale must declare a positive consideration'),
  ('SALE_PARTIAL_SUBDIVISION','TRANSACTION','SHARES_AGAINST_CHILD_PARCEL','sharesAgainstChildParcel','ERROR',
   'Shares are validated against the child parcel being transferred, not the parent parcel'),
  ('GIFT','TRANSACTION','NO_CONSIDERATION','considerationAbsent','ERROR',
   'A gift carries no sale consideration'),
  ('GIFT','TRANSACTION','RELATIONSHIP_REQUIRED','relationshipCategoryPresent','ERROR',
   'Relationship category is required and must exist in the relationship master'),
  ('SETTLEMENT','TRANSACTION','RELATIONSHIP_REQUIRED','relationshipCategoryPresent','ERROR',
   'Relationship category is required and must exist in the relationship master'),
  ('SETTLEMENT','TRANSACTION','BASIS_REQUIRED','basisOfSettlementPresent','ERROR',
   'Basis of settlement is required'),
  ('RELEASE_RELINQUISHMENT','TRANSACTION','RELEASOR_IS_COOWNER','releasorsAreRecordedCoOwners','ERROR',
   'Every releasor must already be a recorded co-owner of the property'),
  ('RELEASE_RELINQUISHMENT','TRANSACTION','RELEASED_SHARE_MATCHES','releasedShareMatchesExisting','ERROR',
   'Share being released must match the releasor''s existing recorded share'),
  ('PARTITION','TRANSACTION','SUBPARCEL_COUNT','subparcelCountAtLeastTwo','ERROR',
   'A partition must produce at least two sub-parcels'),
  ('PARTITION','TRANSACTION','SUBPARCEL_EXTENTS_SUM','subparcelExtentsSumToParent','ERROR',
   'Sub-parcel extents must sum to the parent parcel extent within survey tolerance'),
  ('*','PARTY','AADHAAR_FORMAT','aadhaarIsTwelveDigits','ERROR',
   'Aadhaar number must be exactly 12 digits'),
  ('*','PARTY','PAN_FORMAT','panFormatValid','ERROR',
   'PAN must match the format AAAAA9999A'),
  ('*','PARTY','PAN_REQUIRED_ABOVE_TDS','panPresentAboveTdsThreshold','ERROR',
   'PAN is required where the consideration exceeds the TDS threshold in the fee master'),
  ('*','PARTY','HUF_KARTA_REQUIRED','hufHasKarta','ERROR',
   'A HUF party must record the Karta''s own name and Aadhaar'),
  ('*','PARTY','REPRESENTATIVE_AUTHORITY','representativeHasAuthorityRef','ERROR',
   'An authorised representative must carry an authority / PoA reference'),
  ('*','SURVEY','EXTENT_WITHIN_TOLERANCE','measuredExtentWithinTolerance','WARN',
   'Measured extent differs from the recorded extent beyond the configured tolerance'),
  ('*','SURVEY','GEOMETRY_MIN_POINTS','geometryHasAtLeastThreePoints','ERROR',
   'Captured geometry needs at least three vertices'),
  ('*','PROPERTY','EXTENT_POSITIVE','extentPositive','ERROR',
   'Extent must be greater than zero'),
  ('*','PROPERTY','SURVEY_NO_REQUIRED','surveyNoPresent','ERROR',
   'Survey number is mandatory on every property record');
